Auth flow and HTTP interceptor
tm-pe2/ad-website pull request #72
Opened 2022-03-30 20:12 UTC by DrunkenToast

2022-04-02 15:36 UTC, DrunkenToast commented
Ready for review to close #63 
Depends on auth branch in API.

2022-04-06 11:48 UTC, Dries1234 approved these changes
Looks good!

2022-04-06 12:34 UTC, vdbe commented on src/app/interceptors/auth.interceptor.ts
> +          if (err.status == 401 && err.url?.includes('login')) {
The url should **not** include login

2022-04-07 11:01 UTC, vdbe requested changes

2022-04-07 11:14 UTC, vdbe approved these changes

2022-04-20 12:51 UTC, DrunkenToast commented
The interceptor is ready and behaves according to this image:
![image](https://user-images.githubusercontent.com/20017197/164234314-96554d20-08aa-4b85-8703-e0e67348e9d1.png)

This requires you to **always** use the Angular HttpClient, not for example fetch, if you're requesting data from the API.

2022-04-25 14:36 UTC, merged